"""
Validation script for Phase 2b pipeline fixes
Demonstrates:
1. Restored clean production CSVs
2. Fixed merge logic handles dual-metric sources
3. Unwanted columns are removed
"""
import pandas as pd

wafer_dir = r'\\orshfs.intel.com\ORAnalysis$\1276_MAODATA\Config\etch\AME\tbatson\Defects\BE\outputs\wafer'

print("=" * 80)
print("PHASE 2B PIPELINE FIXES - VALIDATION")
print("=" * 80)

print("\n[1] RESTORED PRODUCTION CSVs")
print("-" * 80)

for fname in ['8M5CL_8M6CL_EXTENDED_60DAY.csv', '8M5CL_8M6CL_EXTENDED.csv']:
    csv_path = f'{wafer_dir}/{fname}'
    try:
        df = pd.read_csv(csv_path, low_memory=False)
        print(f"\n{fname}:")
        print(f"  Rows: {len(df):,}")
        print(f"  Columns: {len(df.columns)}")
        
        # Verify NO UNKNOWN rows exist
        unknown_count = (df["CLASS_BEEP"] == "UNKNOWN").sum()
        print(f"  ✓ CLASS_BEEP=UNKNOWN rows: {unknown_count} (should be 0)")
        
        # Verify no EDI-only rows with null NCDD
        edi_only_ncdd_null = ((df["BEEP_NCDD"].isna()) & (df["BEEP_EDI"].notna())).sum()
        print(f"  ✓ EDI-only rows (NCDD null): {edi_only_ncdd_null} (should be 0)")
        
        # Check that no unwanted columns exist
        unwanted_cols = ['STATUS_EDI', 'CLASS_EDI', 'ZERO_EDI',
                        'STATUS_BEEP_EDI', 'CLASS_BEEP_EDI', 'ZERO_BEEP_EDI',
                        'STATUS_SMP_EDI', 'CLASS_SMP_EDI', 'ZERO_SMP_EDI']
        existing_unwanted = [c for c in unwanted_cols if c in df.columns]
        print(f"  ✓ Unwanted columns: {len(existing_unwanted)} (should be 0)")
        if existing_unwanted:
            print(f"    WARNING: Still present: {existing_unwanted}")
        
        # Spot check that NCDD and EDI metrics both exist
        sample_row = df.iloc[0]
        print(f"  ✓ Sample row BEEP_NCDD: {sample_row['BEEP_NCDD']}")
        print(f"  ✓ Sample row BEEP_EDI: {sample_row['BEEP_EDI']}")
        
    except Exception as e:
        print(f"  ERROR: {e}")

print("\n" + "=" * 80)
print("[2] FIXED MERGE LOGIC FOR DUAL-METRIC SOURCES")
print("-" * 80)
print("""
The merge_and_dedup_raw_sources() function in EXTEND_BENCHMARK.py now:

1. Detects dual-metric NCDD_EDI source files
2. Splits NCDD rows (BEEP_NCDD not null) from EDI rows (BEEP_EDI not null)
3. Deduplicates each metric set separately (keep="last")
4. Joins on wafer key (full outer join) to preserve BOTH metrics
5. Consolidates overlapping columns

Result: Each wafer gets NCDD row + EDI row merged into single output row
        No metric data is lost during deduplication
""")

print("=" * 80)
print("[3] UNWANTED COLUMN CLEANUP IN PROCESSOR")
print("-" * 80)
print("""
The _finalize_dataframe() method now removes:
  - STATUS_EDI
  - CLASS_EDI
  - ZERO_EDI
  - STATUS_BEEP_EDI
  - CLASS_BEEP_EDI
  - ZERO_BEEP_EDI
  - STATUS_SMP_EDI
  - CLASS_SMP_EDI
  - ZERO_SMP_EDI

These columns are automatically dropped before sorting/ordering.
They should NOT be generated by future pipeline runs.
""")

print("=" * 80)
print("READY TO RE-RUN ORCHESTRATOR")
print("=" * 80)
print("""
Next steps:
1. Re-run the orchestrator: python 8M5CL_8M6CL_UPDATE.py
2. Monitor for log messages about:
   - "Dual-metric source detected"
   - "Merged NCDD+EDI: X rows (outer join)"
   - "Removing 0 unwanted columns" (on subsequent runs)
3. Validate no CLASS_BEEP=UNKNOWN rows appear
4. Verify both BEEP_NCDD and BEEP_EDI columns contain data
""")
